/*********************************************************************
 *  AUTHOR: Tomas Soltys                                             *
 *  FILE:   rmlib.h                                                  *
 *  GROUP:  RML                                                      *
 *  TYPE:   main header file (*.h)                                   *
 *  DATE:   21-st January 2012                                       *
 *                                                                   *
 *  DESCRIPTION: RMLib - Range Model Library                         *
 *********************************************************************/

#ifndef RMLIB_H
#define RMLIB_H

#include "rml_boundary_condition.h"
#include "rml_condition.h"
#include "rml_condition_component.h"
#include "rml_cut.h"
#include "rml_eigen_value_solver_conf.h"
#include "rml_element.h"
#include "rml_element_group.h"
#include "rml_entity_group_data.h"
#include "rml_element_shape_derivation.h"
#include "rml_element_shape_function.h"
#include "rml_environment_condition.h"
#include "rml_file_header.h"
#include "rml_file_io.h"
#include "rml_file.h"
#include "rml_file_manager.h"
#include "rml_gl_display_properties.h"
#include "rml_initial_condition.h"
#include "rml_interpolated_element.h"
#include "rml_interpolated_entity.h"
#include "rml_interpolated_node.h"
#include "rml_line.h"
#include "rml_material.h"
#include "rml_material_list.h"
#include "rml_material_property.h"
#include "rml_matrix_solver_conf.h"
#include "rml_mesh_generator.h"
#include "rml_mesh_input.h"
#include "rml_mesh_setup.h"
#include "rml_modal_setup.h"
#include "rml_model_data.h"
#include "rml_model.h"
#include "rml_model_msh.h"
#include "rml_model_stl.h"
#include "rml_model_raw.h"
#include "rml_monitoring_point_manager.h"
#include "rml_monitoring_point.h"
#include "rml_node.h"
#include "rml_patch.h"
#include "rml_patch_book.h"
#include "rml_patch_input.h"
#include "rml_point.h"
#include "rml_polygon.h"
#include "rml_problem_setup.h"
#include "rml_problem_task_item.h"
#include "rml_problem_type.h"
#include "rml_problem.h"
#include "rml_radiation_setup.h"
#include "rml_results.h"
#include "rml_scalar_field.h"
#include "rml_segment.h"
#include "rml_shape_generator.h"
#include "rml_sparse_matrix.h"
#include "rml_sparse_vector.h"
#include "rml_stream_line.h"
#include "rml_surface.h"
#include "rml_tetrahedron.h"
#include "rml_time_solver.h"
#include "rml_triangle.h"
#include "rml_triangulate.h"
#include "rml_variable.h"
#include "rml_variable_data.h"
#include "rml_vector_field.h"
#include "rml_view_factor_matrix.h"
#include "rml_view_factor_matrix_header.h"
#include "rml_view_factor_row.h"
#include "rml_volume.h"

#endif /* RMLIB_H */
